template_path: templates/ec2.py

sceptre_user_data:
  ImageId: ami-0c21ae4a3bd190229
  InstanceType: t2.micro
  SubnetId: !stack_output subnet-public::SubnetId
  SecurityGroupIds:
    - !stack_output security-group::GroupId
  UserData:
    Path: data/userdata.sh
  Tags:
    -
      Key: "Name"
      Value: "httpd-lab1"
    -
      Key: "Environment"
      Value: "Labo"
