template_path: templates/vpc.py

sceptre_user_data:
  CidrBlock: 10.0.0.0/16
  InternetGateway: True
  Tags:
    -
      Key: "Name"
      Value: vpc-{{environment_path.0}}
    -
      Key: "Project"
      Value: {{environment_config.project_code}}
